# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
    run:
        shell: bash

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        set -x  # let us see each command as it runs
        sudo apt-get install --assume-yes tesseract-ocr
        python -m pip install --upgrade pip
        pip install flake8 pytest
        # Collect all the requirements.txt in the repo.
        shopt -s globstar
        mapfile -t reqs < <(printf -- "-r%s\n" **/*/requirements.txt)
        if [[ "${#reqs[@]}" -gt 0 ]]; then
            # Satisfy *all* the requirements.
            pip install "${reqs[@]}"
        fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
